a = int(input())
b = int(input())
c = int(input())
d = int(input())
s = int(input())
res1 = (s // (a + b) * (a - b)) + min(s % (a + b), a) - min(s % (a + b) - a if s % (a + b) - a > 0 else 0, b)
res2 = (s // (c + d) * (c - d)) + min(s % (c + d), c) - min(s % (c + d) - c if s % (c + d) - c > 0 else 0, d)
print('Tied') if res1 == res2 else print('Nikky' if res1 > res2 else 'Byron')